server:
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://192.168.200.188:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.200.188
      port: 6379
      database: 0
      connect-timeout: 18000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期7天
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  auto-renew: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
  is-read-cookie: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 如果你有 XML 映射文件
  type-aliases-package: com.zh.look.bean # 实体类所在的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
