server:
  port: 10087
spring:
  datasource:
    url: jdbc:mysql://192.168.200.188:3306/look?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.200.188
      port: 6379
      database: 0
      connect-timeout: 18000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml # 如果你有 XML 映射文件
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl